name: CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "8.0.302"

      - name: Restore dependencies
        run: dotnet restore ./Y76.sln  

      - name: Build
        run: dotnet build ./Y76.sln --configuration Release  

      - name: Test
        run: dotnet test ./Y76.sln --no-build --verbosity normal 

      - name: Clean up previous publish artifacts
        run: rm -rf ./publish 

      - name: Publish Artifact
        run: dotnet publish ./Y76.sln -c Release -o ./publish  

      - name: Archive Published Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: publish
          path: ./publish  

      - name: Deploy Locally
        run: |
          # Define the path to the published folder
          PUBLISHED_FOLDER="./publish/deploy.sh"

  
          if [ -d "$PUBLISHED_FOLDER" ]; then
              echo "Running the application locally..."
              DLL_FILE=$(ls $PUBLISHED_FOLDER | grep .dll | head -n 1)
              if [ -z "$DLL_FILE" ]; then
                  echo "No DLL file found in the published folder."
              else
                  dotnet "$PUBLISHED_FOLDER/$DLL_FILE" &
                  APP_PID=$!
                  sleep 60 
                  kill $APP_PID
              fi
          else
              echo "Published folder does not exist. Please ensure the build process completed successfully."
          fi
        if: success()
