name: CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "8.0.302"

      - name: Restore dependencies
        run: dotnet restore	

      - name: Build
        run: dotnet build ./Y76.sln --configuration Release

      - name: Test
        run: dotnet test ./Y76.sln --no-build --verbosity normal

      - name: Publish Artifact
        run: dotnet publish Y76.sln -c Release -o ./publish


      - name: Archive Published Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: publish
          path: ./publish
